#!/usr/bin/env python3

from pprint import pprint
import pathlib
import csv
import subprocess
import tomllib
import os
import re
import glob
import git
import argparse
import logging
import json
from build_aux.build_common import *
import build_aux.flatpak_cargo_generator as cg

G_RPM_VERSION = None
G_SRPM_PATH = None
G_MOCK_SRPM_ROOT = None
G_MOCK_RPM_ROOT = None
SPEC_FILE_PATH = None
G_LOCAL_RPM_DIR = "tmp"
G_SOURCES_DIR = f"{G_LOCAL_RPM_DIR}/SOURCES"
G_SPECS_DIR = f"{G_LOCAL_RPM_DIR}/SPECS"
COPR_REPO = "sysd-manager"

APP_ID = "io.github.plrigaux.sysd-manager"
MANIFEST = f"{APP_ID}.yaml"
FLATHUB_DIR = "../flathub"


def main():
    parser = argparse.ArgumentParser(description="Copr RPM builder",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("action", choices=[
        "clean", "build", "run", "lint", "compose", "validate", "flathub", "cargogen"], help="action to perform")

    args = parser.parse_args()

    match args.action:
        case "build":
            build()
        case "clean":
            clean()
        case "run":
            run()
        case "lint":
            lint()
        case "compose":
            compose()
        case "validate":
            validate()
        case "flathub":
            add_required_files()
        case "cargogen":
            cargo_gen()


def clean():
    list_dir = ["builddir", ".flatpak-builder"]

    for dir in list_dir:
        print(f"{color.BOLD}Deleting{color.END} {dir}")
        subprocess.run(["rm", "-fr", dir])


def build():
    subprocess.run(["flatpak-builder",
                    "--force-clean",
                    "--user",
                    "--install-deps-from=flathub",
                    "--mirror-screenshots-url=https://dl.flathub.org/media/",
                    "--repo=repo",
                    "--install",
                    "builddir",
                    MANIFEST])


def run():
    print("Try to run the Flatpack")
    # subprocess.run(["flatpak", "run", "io.github.plrigaux.sysd-manager"])
    subprocess.run(["flatpak", "run", APP_ID])


def lint():
    print(f"{color.BOLD}{color.CYAN}Lint manifest{color.END}")
    subprocess.run(["flatpak", "run", "--command=flatpak-builder-lint",
                    "org.flatpak.Builder", "manifest", MANIFEST])

    print(f"{color.BOLD}{color.CYAN}Lint repo{color.END}")
    subprocess.run(["flatpak", "run", "--command=flatpak-builder-lint",
                   "org.flatpak.Builder", "repo", "repo"])


def compose():
    print(f"{color.BOLD}{color.CYAN}appstreamcli compose{color.END}")
    subprocess.run(["appstreamcli", "compose", "builddir/files"])


def validate():
    print(f"{color.BOLD}{color.CYAN}Validate metainfo.xml{color.END}")
    subprocess.run(["flatpak", "run", "--command=flatpak-builder-lint", "org.flatpak.Builder",
                   "appstream", f"data/metainfo/{APP_ID}.metainfo.xml"])

    lint()


def add_required_files():
    print(f"{color.BOLD}{
          color.CYAN}Add the required files for the submission{color.END}")
    # https://docs.flathub.org/docs/for-app-authors/requirements/#required-files
    subprocess.run(["cp", "-v", MANIFEST, FLATHUB_DIR])


def cargo_gen():
    print(f"{color.BOLD}{color.CYAN}Generate manifest json{
          color.END} from {color.BOLD}Cargo.lock{color.END}")

    outfile = "cargo-sources.json"
    cargo_lock = "Cargo.lock"
    logging.basicConfig(level=logging.DEBUG)
    git_tarballs = False

    generated_sources = cg.asyncio.run(cg.generate_sources(cg.load_toml(cargo_lock),
                                                           git_tarballs=git_tarballs))
    with open(outfile, 'w') as out:
        json.dump(generated_sources, out, indent=4, sort_keys=False)


main()
