#!/usr/bin/env python3

import argparse
import logging
import json

from build_aux.build_common import *
import build_aux.flatpak_cargo_generator as cg
import build_aux.flatpak_cargo_generator as cg

from os import walk

G_RPM_VERSION = None
G_SRPM_PATH = None
G_MOCK_SRPM_ROOT = None
G_MOCK_RPM_ROOT = None
SPEC_FILE_PATH = None
G_LOCAL_RPM_DIR = "tmp"
G_SOURCES_DIR = f"{G_LOCAL_RPM_DIR}/SOURCES"
G_SPECS_DIR = f"{G_LOCAL_RPM_DIR}/SPECS"
COPR_REPO = "sysd-manager"

APP_ID = "io.github.plrigaux.sysd-manager"
MANIFEST = f"{APP_ID}.yaml"
FLATHUB_DIR = "../flathub"
CARGO_LOCK = "Cargo.lock"
CARGO_SOURCES = "cargo-sources.json"


def main():
    parser = argparse.ArgumentParser(
        description="Copr RPM builder",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "action",
        choices=[
            "clean",
            "build",
            "run",
            "lint",
            "compose",
            "validate",
            "flathub",
            "generate",
            "copy",
            "cleanf",
        ],
        help="action to perform",
    )

    parser.add_argument("--logbus", action="store_true", help="log dbus message on run")
    args = parser.parse_args()

    match args.action:
        case "build":
            build()
        case "clean":
            clean()
        case "run":
            run(args.logbus)
        case "lint":
            lint()
        case "compose":
            compose()
        case "validate":
            validate()
        case "flathub":
            add_required_files()
        case "generate":
            generate()
        case "repair":
            repair()
        case "copy":
            set_required_files()
        case "cleanf":
            clean_flathub_dir()
        case _:
            print("No actions performed")


def clean():
    list_dir = ["builddir", ".flatpak-builder", CARGO_SOURCES, "repo"]

    for dir in list_dir:
        print(f"{color.BOLD}Deleting{color.END} {dir}")
        cmd_run(["rm", "-fr", dir])


def build():
    set_required_files()

    print(f"{color.BOLD}{color.CYAN}Building for flatpak{color.END}")

    # Info https://docs.flathub.org/docs/for-app-authors/submission/
    cmd_run(
        [
            # "flatpak",
            # "run",
            # "org.flatpak.Builder",
            "flatpak-builder",
            "--force-clean",
            "--sandbox",
            "--user",
            "--install-deps-from=flathub",
            "--ccache",
            "--mirror-screenshots-url=https://dl.flathub.org/media",
            "--repo=repo",
            "--install",
            "builddir",
            MANIFEST,
        ],
        cwd=FLATHUB_DIR,
    )


def repair():
    cmd_run(["flatpak", "-v", "--user", "repair"])


def run(logbus=False):
    print("Try to run the Flatpack")

    cmd = ["flatpak", "run", APP_ID]
    if logbus:
        cmd.insert(2, "--log-session-bus")

    try:
        cmd_run(cmd)
    except KeyboardInterrupt as ki:
        print("Program closed by Keyboard Interrupt")


def lint():
    print(f"{color.BOLD}{color.CYAN}Lint manifest{color.END}")
    cmd_run(
        [
            "flatpak",
            "run",
            "--command=flatpak-builder-lint",
            "org.flatpak.Builder",
            "manifest",
            MANIFEST,
        ]
    )

    print(f"{color.BOLD}{color.CYAN}Lint repo{color.END}")
    cmd_run(
        [
            "flatpak",
            "run",
            "--command=flatpak-builder-lint",
            "org.flatpak.Builder",
            "repo",
            "repo",
        ]
    )


def compose():
    print(f"{color.BOLD}{color.CYAN}appstreamcli compose{color.END}")
    cmd_run(["appstreamcli", "compose", "builddir/files"])


def validate():
    print(f"{color.BOLD}{color.CYAN}Validating {APP_ID}.metainfo.xml{color.END}")
    cmd_run(
        [
            "flatpak",
            "run",
            "--command=flatpak-builder-lint",
            "org.flatpak.Builder",
            "appstream",
            f"data/metainfo/{APP_ID}.metainfo.xml",
        ]
    )

    lint()


def add_required_files():
    print(
        f"{color.BOLD}{color.CYAN}Add the required files for the submission{color.END}"
    )
    # https://docs.flathub.org/docs/for-app-authors/requirements/#required-files
    cmd_run(["cp", "-v", MANIFEST, FLATHUB_DIR])


def generate():
    print(f"{color.BOLD}{color.CYAN}Generate cargo sources{color.END}")

    loglevel = logging.INFO
    logging.basicConfig(level=loglevel)
    git_tarballs = False

    generated_sources = cg.asyncio.run(
        cg.generate_sources(cg.load_toml(CARGO_LOCK), git_tarballs=git_tarballs)
    )

    cmd_run(["mkdir", "-p", FLATHUB_DIR])

    with open(f"{FLATHUB_DIR}/{CARGO_SOURCES}", "w") as out:
        json.dump(generated_sources, out, indent=4, sort_keys=False)


def diag():
    """flatpak remotes -d
    flatpak update -v --ostree-verbose
    flatpak list"""


def set_required_files():
    # https://docs.flathub.org/docs/for-app-authors/requirements/#required-files
    print(f"{color.BOLD}Add required files for {color.CYAN}Flathub{color.END}")

    cmd_run(["mkdir", "-p", FLATHUB_DIR])

    generate()

    cmd_run(
        [
            "cp",
            "-r",
            "Cargo.toml",
            MANIFEST,
            # CARGO_SOURCES,
            CARGO_LOCK,
            "src",
            "data",
            "build.rs",
            "screenshots",
            f"{FLATHUB_DIR}",
        ]
    )

    ignored = ["/target/", "/.flatpak/", "/.flatpak-builder", "/repo", "/builddir"]
    with open(f"{FLATHUB_DIR}/.gitignore", "w") as file:
        content = "\n".join(ignored)
        file.write(content)


def clean_flathub_dir():

    file_list = []
    for dirpath, dirnames, filenames in walk(FLATHUB_DIR):
        dirnames = [x for x in dirnames if x != ".git"]
        file_list.extend(dirnames)
        file_list.extend(filenames)
        print(f"Path {dirpath}")
        break

    files_to_clean = []
    for file_or_dir in file_list:
        file_or_dir = f"{FLATHUB_DIR}/{file_or_dir}"
        files_to_clean.append(file_or_dir)

    print(files_to_clean)

    for dir in files_to_clean:
        print(f"{color.BOLD}Deleting{color.END} {dir}")
        cmd_run(["rm", "-fr", dir])


main()
