# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

Name:           sysd-manager
Version:        0.0.2
Release:        %autorelease
Summary:        GUI to manage systemd units

SourceLicense:  GPLv3+
# FIXME: paste output of %%cargo_license_summary here
License:        GPL-3.0-or-later
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/plrigaux/sysd-manager
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A GUI to manage systemd units.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENCE
%license LICENSE.dependencies
%doc README.md
%doc meson_options.txt
%{_bindir}/sysd-manager

%changelog
%autochangelog
