#!/usr/bin/env python3
import ubuntu.packageunbuntu as deb

import appimage.build_appimage as aim
import aur.packaging as pacaur
import build_aux.build_common as bc
import build_aux.tag_version as tag
import flathub.goflathub as gof
import nix.pacnix as nix
from build_aux.build_common import color

# to ensure that evrything works before scrapping a version number
bc.cmd_run(["cargo", "build", "--release", "--features", "appimage"], cwd="..")

tag.tag()
tag.create_release()
pacaur.generate_and_push()
gof.deploy()
aim.publish()
nix.create()
deb.cargo_publish()

print(f"{color.GREEN}{color.BOLD}--------------------{color.END}")
print(f"{color.GREEN}{color.BOLD}Publishing on Crate.io {color.END}")
print(f"{color.GREEN}{color.BOLD}--------------------{color.END}")

bc.cmd_run(["cargo", "publish"], cwd="sysd-manager-base", on_fail_exit=False)
bc.cmd_run(["cargo", "publish"], cwd="sysd-manager-comcontroler", on_fail_exit=False)
bc.cmd_run(["cargo", "publish"], cwd=".")
