#!/usr/bin/env python3
import build_aux.tag_version as tag
import aur.packaging as pacaur
import flathub.goflathub as gof
import appimage.build_appimage as aim
tag.main()
pacaur.generate_and_push()
gof.deploy()
#aim.publish()



from build_aux.build_common import color
import build_aux.build_common as bc

print(f"{color.GREEN}{color.BOLD}--------------------{color.END}")
print(f"{color.GREEN}{color.BOLD}Publishing on Crate.io {color.END}")
print(f"{color.GREEN}{color.BOLD}--------------------{color.END}")

bc.cmd_run(["cargo", "publish"], cwd="sysd-manager-base")
bc.cmd_run(["cargo", "publish"], cwd="sysd-manager-comcontroler")
bc.cmd_run(["cargo", "publish"], cwd=".")
