#!/usr/bin/env python3
import build_aux.build_common as bc
from  build_aux.build_common import color
import os

os.chdir("..")

bc.exit_if_dirty()


#check git changes
if (bc.cmd_run("[[ -z \"$(git status -s)\" ]]", shell=True, on_fail_exit=False) != 0):   
    bc.cmd_run(["git", "add", "CHANGELOG.md"], on_fail_exit=False)
    tag_name = bc.get_version_tag()
    bc.cmd_run(["git", "commit", "-m", f"change log {tag_name}"], on_fail_exit=False)
    bc.cmd_run(["git", "push"], on_fail_exit=False)

bc.version(False, None, False)